name: Reviewer PR based on file extensions

on:
  pull_request:
    types: [opened]

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # 최신 LTS 버전으로 설정 (현재 LTS 버전: 18)

    - name: Install dependencies
      run: npm install @actions/core @actions/github

    - name: Run custom script
      run: node .github/scripts/reviwer-pr.js
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        REVIWER_JAVA: ${{ vars.REVIWER_JAVA }}
        REVIWER_PYTHON: ${{ vars.REVIWER_PYTHON }}
        REVIWER_JAVASCRIPT: ${{ vars.REVIWER_JAVASCRIPT }}
        REVIWER_CPP: ${{ vars.REVIWER_CPP }}
        ACTOR: ${{ github.actor }}
        
